/**
 * Build script for @attrus/cabiros.
 *
 * Assembles a clean, publishable `dist/` from the source files under `src/`.
 * No bundler / no runtime deps.
 *
 * Source layout:
 *   src/tokens/*.css        -> design tokens, split by concern (3-layer arch)
 *   src/typography/index.css -> ready-to-use type classes + utilities
 *   src/components/*.css     -> one stylesheet per component domain
 *   src/index.css            -> dev entry (CDN fonts + all of the above)
 *
 * Output (published artifact — stable, do not break consumer paths):
 *   dist/css/tokens.css        -> all token partials + type classes, concatenated
 *   dist/css/fonts.css         -> @font-face for the bundled woff2 files
 *   dist/css/components/*.css  -> copies of src/components/*.css (barrel excluded)
 *   dist/css/index.css         -> imports fonts + tokens + every component
 *   dist/fonts/*.woff2         -> Lato + JetBrains Mono (from @fontsource)
 *   dist/tokens/*.json         -> machine-readable token export
 *   dist/assets/**             -> brand logos, icons, country flags (SVG)
 *   dist/react/**              -> typed React components (TSX source + .d.ts)
 */
import { fileURLToPath } from "node:url";
import path from "node:path";
import fs from "node:fs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const src = path.join(root, "src");
const dist = path.join(root, "dist");

/* ------------------------------------------------------------------ helpers */
const read = (p) => fs.readFileSync(p, "utf8");
const write = (p, c) => {
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, c);
};
const copy = (from, to) => {
  fs.mkdirSync(path.dirname(to), { recursive: true });
  fs.copyFileSync(from, to);
};
// Manual recursive copy — fs.cpSync throws EIO on some OneDrive-backed paths.
const copyDir = (from, to) => {
  fs.mkdirSync(to, { recursive: true });
  for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
    const srcPath = path.join(from, entry.name);
    const dstPath = path.join(to, entry.name);
    if (entry.isDirectory()) copyDir(srcPath, dstPath);
    else fs.copyFileSync(srcPath, dstPath);
  }
};

/* ------------------------------------------------ 0. clean output directory */
fs.rmSync(dist, { recursive: true, force: true });

/* --------------------------------------------------------------- 1. fonts */
// Weights/styles actually referenced by the design system.
const FONTS = [
  {
    pkg: "@fontsource/lato",
    family: "Lato",
    prefix: "lato-latin",
    license: "LICENSE-Lato.txt",
    faces: [
      { weight: 100, style: "normal" },
      { weight: 300, style: "normal" },
      { weight: 300, style: "italic" },
      { weight: 400, style: "normal" },
      { weight: 400, style: "italic" },
      { weight: 700, style: "normal" },
      { weight: 700, style: "italic" },
      { weight: 900, style: "normal" },
    ],
  },
  {
    pkg: "@fontsource/jetbrains-mono",
    family: "JetBrains Mono",
    prefix: "jetbrains-mono-latin",
    license: "LICENSE-JetBrainsMono.txt",
    faces: [
      { weight: 400, style: "normal" },
      { weight: 500, style: "normal" },
      { weight: 600, style: "normal" },
    ],
  },
];

let fontFaces = `/* ATTRUS / Cabiros — bundled web fonts (self-hosted, no CDN).
   Generated by scripts/build.mjs. Fonts under SIL OFL — see dist/fonts/LICENSE-*.txt */\n\n`;

for (const font of FONTS) {
  const filesDir = path.join(root, "node_modules", font.pkg, "files");
  // Bundle the license alongside the font files.
  const licenseSrc = path.join(root, "node_modules", font.pkg, "LICENSE");
  if (fs.existsSync(licenseSrc)) {
    copy(licenseSrc, path.join(dist, "fonts", font.license));
  }

  for (const face of font.faces) {
    const fileName = `${font.prefix}-${face.weight}-${face.style}.woff2`;
    const srcFile = path.join(filesDir, fileName);
    if (!fs.existsSync(srcFile)) {
      throw new Error(`Missing font file: ${srcFile}. Did you run npm install?`);
    }
    copy(srcFile, path.join(dist, "fonts", fileName));
    fontFaces +=
      `@font-face {\n` +
      `  font-family: "${font.family}";\n` +
      `  font-style: ${face.style};\n` +
      `  font-weight: ${face.weight};\n` +
      `  font-display: swap;\n` +
      `  src: url("../fonts/${fileName}") format("woff2");\n` +
      `}\n\n`;
  }
}

write(path.join(dist, "css", "fonts.css"), fontFaces);

/* ------------------------------------------------------------- 2. tokens.css */
// Concatenate the token partials + type classes into a single published file.
// Order mirrors src/tokens/index.css (cascade order), then the type classes.
// Any stray CDN @import lines are stripped (fonts are self-hosted via fonts.css).
const TOKEN_PARTIALS = [
  "tokens/palette.css",
  "tokens/color-semantic.css",
  "tokens/gradients.css",
  "tokens/data-viz.css",
  "tokens/glass.css",
  "tokens/radius.css",
  "tokens/elevation.css",
  "tokens/spacing.css",
  "tokens/iconography.css",
  "tokens/motion.css",
  "tokens/typography.css",
  "tokens/theme-dark.css",
  "typography/index.css",
];

const stripCdnImports = (css) =>
  css
    .split("\n")
    .filter((line) => !/^\s*@import\s+url\(['"]?https?:\/\//.test(line))
    .join("\n");

let tokensCss = `/* @attrus/cabiros — design tokens + type classes (concatenated).
   Generated by scripts/build.mjs from src/tokens/ and src/typography/. */\n\n`;
for (const rel of TOKEN_PARTIALS) {
  tokensCss += stripCdnImports(read(path.join(src, rel))).trimEnd() + "\n\n";
}
write(path.join(dist, "css", "tokens.css"), tokensCss);

/* --------------------------------------------------------- 3. component css */
const EXCLUDE = new Set(["index.css"]); // barrel — dist gets its own index.css
const componentsSrcDir = path.join(src, "components");
const components = fs
  .readdirSync(componentsSrcDir)
  .filter((f) => f.endsWith(".css") && !EXCLUDE.has(f))
  .sort();

for (const file of components) {
  copy(
    path.join(componentsSrcDir, file),
    path.join(dist, "css", "components", file)
  );
}

/* ------------------------------------------------------------- 4. index.css */
let index = `/* @attrus/cabiros — full design system stylesheet.
   Order matters: fonts -> tokens -> components. */\n\n`;
index += `@import "./fonts.css";\n`;
index += `@import "./tokens.css";\n\n`;
for (const file of components) {
  index += `@import "./components/${file}";\n`;
}
write(path.join(dist, "css", "index.css"), index);

/* --------------------------------------------------------------- 5. tokens */
const exportDir = path.join(root, "export");
for (const file of fs.readdirSync(exportDir)) {
  if (file.endsWith(".json")) {
    copy(path.join(exportDir, file), path.join(dist, "tokens", file));
  }
}

/* --------------------------------------------------------------- 6. assets */
const assetsSrc = path.join(root, "assets");
copyDir(assetsSrc, path.join(dist, "assets"));

/* ---------------------------------------------------------------- 7. react */
// Typed React layer — shipped as source (TSX + .d.ts contracts + index
// barrel). No compilation: the consumer's toolchain builds them. The CSS
// stays the single visual source of truth; TSX only composes class names.
const reactSrc = path.join(src, "react");
let reactFiles = 0;
let reactComponents = 0;
if (fs.existsSync(reactSrc)) {
  copyDir(reactSrc, path.join(dist, "react"));
  for (const entry of fs.readdirSync(reactSrc, { withFileTypes: true })) {
    if (entry.isDirectory()) reactComponents += 1;
  }
  const countFiles = (dir) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (entry.isDirectory()) countFiles(path.join(dir, entry.name));
      else reactFiles += 1;
    }
  };
  countFiles(reactSrc);
}

/* ------------------------------------------------------------------ report */
const fontCount = FONTS.reduce((n, f) => n + f.faces.length, 0);
console.log("Built dist/:");
console.log(`  css/tokens.css      (${TOKEN_PARTIALS.length} partials concatenated, CDN @import stripped)`);
console.log(`  css/fonts.css       (${fontCount} @font-face)`);
console.log(`  css/components/     (${components.length} files)`);
console.log(`  css/index.css       (full bundle)`);
console.log(`  fonts/              (${fontCount} woff2 + licenses)`);
console.log(`  tokens/             (json export)`);
console.log(`  assets/             (svg)`);
console.log(`  react/              (${reactComponents} components, ${reactFiles} source files)`);
