name: Notify Teams

on:
  release:
    types: [published]

jobs:
  notify-sandbox:
    if: github.event.release.prerelease == true
    permissions:
      actions: read
      contents: read
    uses: FacilitaGPI/github-workflows/.github/workflows/notify-teams.yaml@main
    with:
      environment: sandbox
    secrets: inherit

  notify-production:
    if: github.event.release.prerelease == false
    permissions:
      actions: read
      contents: read
    uses: FacilitaGPI/github-workflows/.github/workflows/notify-teams.yaml@main
    with:
      environment: production
    secrets: inherit
